version: "2"
services:
  gateway:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - "SPRING_PROFILES_ACTIVE=prod,swagger"
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - "EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka"
      - "SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://gateway-postgresql:5432/Gateway"
      - "SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://129.69.217.173:9080/auth/realms/jhipster"
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
    restart: always
    ports:
      - "8080:8080"
    networks:
      - it-rex
      - default

  gateway-postgresql:
    image: "postgres:12.3"
    environment:
      - POSTGRES_USER=Gateway
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - default

networks:
  it-rex:
    external: true
